/*
 * This source file was generated by the Gradle 'init' task
 */
package org.seattleoba.lambda;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

class BevyTicketDynamodbEventHandlerTest {
    @Test
    void eventHandler() {
        BevyTicketDynamodbEventHandler classUnderTest = new BevyTicketDynamodbEventHandler("", "");

        assertDoesNotThrow(() -> classUnderTest.handleRequest(null, null));
    }
}
